version: '3'

services:
  golang:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gustcoder/go-graphql
    container_name: go-graphql
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - .:/usr/src/app