version: '3'

services:
  laravel:
    build: 
      context: ./laravel/example-app
      dockerfile: Dockerfile.prod
    image: gustcoder/laravel:prod
    container_name: laravel-prod
    networks:
      - laranet

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: gustcoder/nginx:prod
    container_name: nginx-prod
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge      